from django.db import models
from django.contrib.auth import get_user_model

# Best Practice: Use get_user_model() to reference the user class.
# This ensures compatibility if you swap the default User model for a custom one.
User = get_user_model()


class Payment(models.Model):
    """
    Represents a financial transaction for an order.
    
    This records the attempt to pay via a gateway (e.g., Paystack).
    It tracks the status and links the payment to a specific Order and User.
    """

    # The user who initiated the payment.
    # null=True allows for guest checkouts (if your app supports that),
    # otherwise, you might want to enforce this.
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name="payments"
    )

    # The specific Order this payment is for.
    # We use a string reference "orders.Order" to avoid circular import errors
    # (i.e., if models.py in 'orders' also tries to import 'payments').
    order = models.ForeignKey(
        "orders.Order", on_delete=models.CASCADE, related_name="payments"
    )

    # The unique transaction reference code generated by the payment gateway (Paystack).
    # unique=True is critical here to prevent double-charging or duplicate records.
    reference = models.CharField(max_length=100, unique=True)

    # The amount paid.
    # Always use DecimalField for currency to avoid floating-point math errors.
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    # Tracks the state of the transaction.
    status = models.CharField(
        max_length=20,
        choices=[
            ("pending", "Pending"),    # Created, sent to gateway
            ("completed", "Completed"), # Gateway confirmed success
            ("failed", "Failed"),      # Gateway returned error
        ],
        default="pending",
    )

    # A boolean flag for quick checks (e.g., if payment.verified: ship_order())
    verified = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """String representation: e.g., 'user@email.com - 5000.00'"""
        return f"{self.user} - {self.amount}"
