
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

# DRF Imports
from rest_framework import permissions
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token

# JWT Imports (SimpleJWT)
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

# Swagger / API Documentation Imports
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

# Local Views
from . import views

# --- Router Configuration ---
# The DefaultRouter automatically creates the URL conf for ViewSets.
# Example: 'tickets/' -> List/Create, 'tickets/<id>/' -> Retrieve/Update/Delete.
router = DefaultRouter()
router.register(r'tickets', views.TicketViewSet)
router.register(r'responses', views.ResponseViewSet)
router.register(r'feedbacks', views.FeedbackViewSet)

# --- Swagger Schema Configuration ---
# This sets up the automatic API documentation generator.
schema_view = get_schema_view(
    openapi.Info(
        title="Customer Care API",
        default_version='v1',
        description="API documentation for the Customer Care module",
        terms_of_service="[https://www.google.com/policies/terms/](https://www.google.com/policies/terms/)",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # --- Django Admin ---
    path('admin/', admin.site.urls),

    # --- Main API Endpoints ---
    # Includes all URLs generated by the router (tickets, responses, feedback)
    path('api/', include(router.urls)),

    # --- Authentication Endpoints ---
    
    # 1. DRF Standard Token Auth
    # Returns a static token. Good for simple apps, but doesn't expire automatically.
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),

    # 2. JWT (JSON Web Token) Auth
    # Recommended for modern SPAs (React/Vue) and Mobile Apps.
    # - obtain_pair: Login (sends username/password) -> Returns Access + Refresh tokens.
    # - refresh: Send Refresh token -> Get new Access token.
    # - verify: Check if a token is valid.
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

    # --- Documentation Endpoints ---
    # Swagger UI (Interactive)
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    # ReDoc UI (Clean, static-style documentation)
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# The line above serves static files (CSS/JS) during development.
